// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plwkinncdahvqzjcarlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsd2tpbm5jZGFodnF6amNhcmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjY3MzUsImV4cCI6MjA2ODkwMjczNX0.g6Nq23fFW8EaXUaKc10roaRBey7wFHprzDx7DQfvKdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});